#!/usr/bin/env python

"""
Created on July 2, 2017
@author: Soroosh Sohangir
"""

import logging
import sys

if __name__ == '__main__':
    logger = logging.getLogger(__name__)

    if len(sys.argv) < 2:
        print('Syntax: %s package' % (sys.argv[0],))

    else:
        __import__(sys.argv[1], globals(), locals(), ['main'], 0).main()

